### PR TITLE
Don't include target/ directory element on output tar

### PR DESCRIPTION
**Pull request by dobladez**
I see that the generated archive contained all jar files under a `lib/target/` directory.

I think it'd be better to chop 'target/' off, so the jar files end up under `lib/`. This is my intention with this patch.

Now, this might break some people's existing scripts... So, if you agree on accepting this change, we'd have to bump the minor version number and add a notice about this change on the README.

Thanks!

### CODE REVIEW

**Comment by technomancy** [comment]
That sounds good to me; also the change you mentioned on IRC about placing the tar file in `:target-path` by default sounds good. Would you mind describing the changes in the readme? I can cut a 3.0.0 release since it's a breaking change.

**Comment by dobladez** [comment]
There you go. Let me know if you'd like me to adjust the wording or anything.
Note that I didn't touch the project version. Also, note that I re-based this branch.

Thanks

**Comment by technomancy** [comment]
No problem. 3.0.0 is out on clojars.

**Comment by dobladez** [comment]
Excellent, thanks!

**Pull request merged**
