### PR TITLE
Two sets of changes

### PR DESCRIPTION
**Pull request by joegallo**
1. Makes things work with lein 2.5.0
2. Allows one to specify a :leading-path inside the tar, which can even be empty

cc/ @dacamo76 -- I think this would give you the option you need, right?

### CODE REVIEW

**Comment by joegallo** [comment]
I'm not sure how important it is to support older versions of leiningen, but there's some strange behavior with lein-tar and lein 2.2.0. I'm sortof inclined to just ignore it, as nobody has complained yet.

So far things look okay with this pr and older versions besides that, though.

**Comment by joegallo** [comment]
Okay, I'm done testing, I think everything works fine. Yay!

**Comment by dacamo76** [comment]
Looks good. It even keeps the directory entries. :+1:

**Comment by leathekd** [comment]
@joegallo lgtm, +1

**Comment by leathekd** [comment]
Actually, could you update the readme before merging?

**Comment by technomancy** [comment]
Maybe you could issue a warning if an older version of Leiningen is detected?

**Comment by joegallo** [comment]
@leathekd reorganized the README, per your request -- does this look alright to you?

**Comment by joegallo** [comment]
@technomancy mmm... tell me more about this warning.

**Comment by joegallo** [comment]
I also pulled in @dacamo76's canonical path change, which seemed like a very reasonable one to me.

**Comment by leathekd** [comment]
[Wunderbar!](http://www.oktoberfeestartiesten.nl/typo3temp/pics/Otto_W_persfoto_2013_e5e044c693.jpg)  Thanks!

**Comment by joegallo** [comment]
@technomancy I added a fix for the issue with lein 2.2.0, we should be all set now.

**Comment by technomancy** [comment]
Great. Feel free to merge and cut a release; let me know if you need clojars access.

**Pull request merged**
